### ISSUE TITLE
Compatability Documentation Request

### ISSUE THREAD

**Issue by rewardone** [ChandlerSystems/dropmqttapi#2]
I saw the DROP integration released with Home Assistant 2024.1. Set up instructions currently say: 

> In the Hub Network Settings section on the System > Advanced page, tap the Configure MQTT button.

My app only shows Wifi settings: Current connected network, Join New WiFi Network, Leave WiFi Network

I'm using the (as of now) latest version of the iOS DROP Connect app: 1.0.52
My devices include: 
HUB 2 - firmware: 2.13
Protect valve - firmware: 1.31/1.16
Leak detector(s) - firmware: 1.28 

Requesting information on if my system will be compatible or how to use this library, as I am eager to have this system integrated.

**Comment by pfrazer** [comment]
Hi @rewardone - You are correct that the controls for MQTT connection are not yet available in the DROP Connect app. The DROP firmware and app updates that will enable MQTT integration with Home Assistant should start beta testing sometime next week.

The minimum hub firmware versions to connect with Home Assistant are 1.84 (Hub 1) and 2.14 (Hub 2). These firmware versions will be carried by app versions 1.1.32 (Android) and 1.0.53 (iOS).

I will leave this issue open until the new apps and firmware are fully available to all users, and I will also update the issue with information about getting beta versions of the DROP Connect apps once the apps have begun beta testing.

**Comment by pfrazer** [comment]
The DROP Connect app and firmware versions mentioned above are now available in the DROP beta test programs.  If you install these app and firmware versions, you will find the 'Configure MQTT' button on the DROP Connect app **System > Advanced** page.

For Android devices, go to the [DROP Connect](https://play.google.com/store/apps/details?id=com.chandlersystemsinc.dropconnect) Google Play Store listing and find the 'Join the beta' section of the store listing.

For iOS devices, use the DROP Connect [Testflight invitation](https://testflight.apple.com/join/2HLdpc8H).  This link will provide instructions for installing TestFlight and joining the DROP beta program.

**Comment by rewardone** [comment]
I've successfully enrolled in Testflight and updated DROP Connect. 
I have not had success upgrading the firmware on the Hub. Tests were performed while connected to Wifi.

Firmware update is detected
Update firmware shows Current (2.13) and Available (2.14). 
The firmware downloads and sends to the hub. 
I get the notice that DROP will install the firmware and restart. 

When connecting to the Hub again, the firmware shows 2.13 and that there is a firmware update. 

I've triggered restarts through the app and I have physically restarted the hub. The hub continues to show 2.13.

**Comment by rewardone** [comment]
The above was done with "Automatic firmware updates" toggled on. I did just successfully upgrade firmware after performing the update process with "Automatic firmware updates" toggled off. Yay!

**Comment by pfrazer** [comment]
Interesting.  The automatic firmware updates setting should have no effect on installing updates through the app.  It's possible that the successful update after changing that setting was a coincidence, but we will put it on the list for further testing.  Thanks for the additional information.

**Comment by rewardone** [comment]
It seems DROP doesn't like configuring SSL. Usually, I can use my (non-public, Let's Encrypt) home assisstant's FQDN to connect over 8883. Some things I've noticed. 

1. Subsequent changes to the information in the MQTT API Settings page and then hitting 'connect' does not seem to re-send the connection data. I have to quit DROP Connect and enter data again through the MQTT API Settings page to retry. 
2. The settings using FQDN connects to the broker with an SSL error: 
```
2024-01-10 10:54:03: New connection from 192.168.1.131:53492 on port 8883.
2024-01-10 10:54:03: OpenSSL Error[0]: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
2024-01-10 10:54:03: Client <unknown> disconnected: Protocol error.
```
3. The hostname/IP field does not seem to initiate a connection when a prefix is used with hostname (e.g. ssl://homeassistant.fqdn)

Please let me know if these should be split into separate issues or if continuing to post within this issue is acceptable.

**Comment by pfrazer** [comment]
Since the DROP software is not open-source, we typically encourage users to contact us at feedback@dropconnect.com with issues they have encountered.  However, let's continue discussing these issues in this thread, for now.  Since this is new functionality perhaps it will be helpful for anyone who references this issue.

> Subsequent changes to the information in the MQTT API Settings page and then hitting 'connect' does not seem to re-send the connection data.

So far, I have been unable to reproduce this problem.  Using the iOS DROP app, I am seeing the MQTT configuration being delivered to the hub with each press of the 'Connect' button, regardless of whether or not the data in the form has changed.  I will continue testing to try to reproduce the behavior that you're seeing.

> It seems DROP doesn't like configuring SSL.

Currently, the DROP hub will only do standard MQTT on port 1883.  I will add some text to the app making this more clear.  Adding SSL support to the MQTT module on the DROP hub is non-trivial, but could be included in a future firmware release.  For the time being, it is assumed that the DROP hub is running on the same (local and trusted) network as the MQTT broker.

> The hostname/IP field does not seem to initiate a connection when a prefix is used with hostname

Whatever is entered into the hostname/IP field needs to be resolvable by the DNS client running on the DROP hub.  We recommend simply entering the IP address of your MQTT broker.  (this may require that you create a DHCP reservation on your router to ensure that it's static)  The DNS client on the hub begins by using the DNS server specified in the DHCP lease.  However, if it fails to connect to the resolved IP address when connecting to our remote connectivity servers, it will shift the DNS server to one of three other options (Google, Cloudflare and OpenDNS)  This is necessary because we have seen instances of users' ISPs with broken DNS resolution disabling remote connectivity on DROP hubs.  The fallback to other DNS servers fixes that problem, but means that resolution of a locally defined FQDN may not work.  We will look into making local FQDN resolution work, but for now please start with just the IP address of your broker.

**Comment by rewardone** [comment]
> > Subsequent changes to the information in the MQTT API Settings page and then hitting 'connect' does not seem to re-send the connection data.
> 
> So far, I have been unable to reproduce this problem. Using the iOS DROP app, I am seeing the MQTT configuration being delivered to the hub with each press of the 'Connect' button, regardless of whether or not the data in the form has changed. I will continue testing to try to reproduce the behavior that you're seeing.
> 
I must have been doing weird things or not waiting long enough for my broker's logs. Concur, as long as I'm using an IP or hostname (no prefix), retry attempts are sent correctly with each request. 

>  For the time being, it is assumed that the DROP hub is running on the same (local and trusted) network as the MQTT broker.

Understood. I did see at least one call out in the information box about it running on a trusted network. 

I got a successful connection on 1883:
2024-01-10 13:36:43: New client connected from <local>:58258 as DROP-<id> (p2, c1, k60, u'mqtt_drop')

but no data seems to be posted to any topics. I went into MQTT settings and started listening on topic #, which my mqtt_drop user currently has readwrite access to, but no data was listed while listening was active. 

The MQTT integration did not add any new devices. 

MQTT integration debug logging doesn't generate any logs. 
The Mosquitto broker logs in Home Assistant don't show anything related to data or topics. 

Interestingly, it does seem that my drop user is the only one experiencing timeouts: 
2024-01-10 14:06:41: New client connected from <local>:61222 as DROP-<id> (p2, c1, k60, u'mqtt_drop').
2024-01-10 14:08:16: Client DROP-<id> has exceeded timeout, disconnecting.

Home Assistant: 
 OS: 11.4
 Core: 2024.1.2
 Supervisor: 2023.12.0
Mosquitto: 6.4.0

**Comment by pfrazer** [comment]
Can I assume that you redacted your DROP hub ID and IP address from the log entries you quoted?  If not, there's something really interesting going on.  If so, then that looks normal to me.

The DROP hub should publish discovery information any time it connects to the MQTT broker, any device status changes on the hub (e.g. a device comes online), if you tap the 'Discover' button in the MQTT API settings dialog in the DROP app, or if Home Assistant signals that it just came online.  Discovery payloads are published to (e.g.) `drop_connect/discovery/DROP-2_AA9875/N`, where `N` is a device number.  If the hub is connected to the MQTT broker, you should see a discovery payload for each of your DROP devices when you tap the 'Discover' button in the app.

When data on the DROP hub changes, it publishes the updates to (e.g.) `drop_connect/DROP-2_AA9875/data/N`, where `N` is again a device number.  The hub subscribes to (e.g.) `drop_connect/DROP-2_AA9875/cmd/#` to listen for changes in water and bypass states and the Protect Mode setting.

I'm running the same HA and Mosquitto versions that you cited.  I don't see the 'exceeded timeout' messages that you are seeing, but I am seeing a disconnect/reconnect every two minutes on my HA instance in my home.  Perhaps I need to add an MQTT heartbeat to keep the connection alive.  I'll look into that.  Interestingly, though, I'm not seeing those periodic disconnect/reconnects on my development instance in my office, and I have several hubs connected to it.  Regardless, the periodic reconnects shouldn't affect functionality, they're just unnecessary.

I also can go to the MQTT settings in the HA UI, subscribe to `#` and I see both the discovery and data payloads.  I would expect that to work for you.  If you're not seeing the discovery payloads, that would explain why the DROP devices are not being discovered by HA.  It isn't seeing the discovery payloads either.

How did you add the 'mqtt_drop' user?  Is it a HA user or was it added to the Mosquitto broker 'Logins' option in its configuration?

**Comment by rewardone** [comment]
> Can I assume that you redacted your DROP hub ID and IP address from the log entries you quoted?

Yes, that was me. Probably doesn't really matter since none of it is public, but it's a habit of mine. 

> The DROP hub should publish discovery information any time it connects to the MQTT broker, any device status changes on the hub (e.g. a device comes online), if you tap the 'Discover' button in the MQTT API settings dialog in the DROP app, or if Home Assistant signals that it just came online. Discovery payloads are published to (e.g.) `drop_connect/discovery/DROP-2_AA9875/N`, where `N` is a device number. If the hub is connected to the MQTT broker, you should see a discovery payload for each of your DROP devices when you tap the 'Discover' button in the app.

Hm, I don't see a "Discover" button in the MQTT API settings. Only a 'More Information' button in the top right, the connection form with the connect button, and 'Close'. Even after clicking "OK" on the "Connection Credentials Sent" popup and seeing the connection in Mosquitto, the MQTT API Settings form never changes (I kind of expected 'saved' connection information and status). 

> When data on the DROP hub changes, it publishes the updates to (e.g.) `drop_connect/DROP-2_AA9875/data/N`, where `N` is again a device number. The hub subscribes to (e.g.) `drop_connect/DROP-2_AA9875/cmd/#` to listen for changes in water and bypass states and the Protect Mode setting.

I see homeassistant/status and then messages from other devices. Even though my ACL allows my mqtt_drop user access to all topics, I'll see if specifically adding drop_connect/DROP-3_{id}/# to the accesscontrollist changes anything.

> I also can go to the MQTT settings in the HA UI, subscribe to `#` and I see both the discovery and data payloads. I would expect that to work for you. If you're not seeing the discovery payloads, that would explain why the DROP devices are not being discovered by HA. It isn't seeing the discovery payloads either.
> 
> How did you add the 'mqtt_drop' user? Is it a HA user or was it added to the Mosquitto broker 'Logins' option in its configuration?

mqtt_drop user is a HA user. Local access and non-Admin. Simple alphanumeric password for now since large/complex passwords have caused issues for me before.

**Comment by rewardone** [comment]
> I see homeassistant/status and then messages from other devices. Even though my ACL allows my mqtt_drop user access to all topics, I'll see if specifically adding drop_connect/DROP-3_{id}/# to the accesscontrollist changes anything.

I don't know specifically if this was it, but I modified my ACL: Removed # and added drop_connect/DROP-3_{id}/data/# and drop_connect/DROP-3_{id}/cmd/#. Restarted everything again. Now am seeing the messages posted to the drop_connect topic. 

Successful publishing also grants access to the MQTT API Settings popup with status (e.g. connected to, 'Discover' button, etc.). 

Does the hub need access to homeassistant/{sensor} topics? I'm seeing data in drop_connect, but no devices or entities in MQTT.

With further testing, I thought it was the MQTT integration's MQTT Protocol version (mine is set to 5), but I think I narrowed it down to the accesscontrollist. If the mqtt_drop user is granted topic readwrite #, the app seems to think that the connection/publish wasn't successful (e.g. only presenting a connect screen even though it is connected and publishing data to the broker (from a previous success?)). Even granting readwrite homeassistant/# seems to break the connection for some reason.

I don't know why this would cause issues. Maybe something else in my ACL is messing it up.

**Comment by pfrazer** [comment]
> Hm, I don't see a "Discover" button in the MQTT API settings.

The DROP hub reports to the app whether or not it is connected to an MQTT broker.  If the hub is connected to the broker, then the app displays the current connection status, a 'Disconnect' button and the 'Discover' button.  If the hub is not connected to the broker, then you see the credentials form and the 'Connect' button.  If you see the credentials form instead of the 'Disconnect' and 'Discover' buttons, the hub isn't currently connected to the MQTT broker.

I suspect the problem is related to your ACL or how users created by Home Assistant are interacting with Mosquitto.  Please try testing a user that is defined directly in Mosquitto. Go to the Mosquitto add-on and click on the **Configuration** tab.  In the **Logins** option, create a new user by adding text similar to this:

```yaml
- username: drop_test
  password: unique_password
```

Connecting the DROP hub to the MQTT broker using that user should work, and will let you start to explore the DROP integration in HA.  Afterwards, we can start to experiment with how the differences between Mosquitto users and HA users affect the communication.  I have been testing with users created in Mosquitto simply because that's how most people are likely to set them up.

> Does the hub need access to homeassistant/{sensor} topics?

No, the hub only subscribes to `homeassistant/status` and `drop_connect/DROP-{id}/cmd/#`.  It will only publish on `drop_connect/discovery/DROP-{id}/#` and `drop_connect/DROP-{id}/data/#`

**Comment by rewardone** [comment]
I think this may have to do with data from other topics. I set up a local Mosquitto user and had the same trouble, but found the debug option for the broker. 

When connecting to the broker, DROP requests a subscription to homeassistant/#
```
2024-01-11 11:31:20: Received SUBSCRIBE from DROP-3_{id}
2024-01-11 11:31:20: 	homeassistant/# (QoS 0)
2024-01-11 11:26:30: DROP-3_{id} 0 homeassistant/#
2024-01-11 11:26:30: Sending SUBACK to DROP-3_{id}
```

Mosquitto was then sending PUBLISH from homeassistant/<sensor>/<device> to DROP. 

```
2024-01-11 11:26:30: Sending PUBLISH to DROP-3_{id} (d0, q0, r1, m0, 'homeassistant/cover/<device>/config', ... (470 bytes))
2024-01-11 11:26:30: Sending PUBLISH to DROP-3_{id} (d0, q0, r1, m0, 'homeassistant/light/<device>/config', ... (425 bytes))
2024-01-11 11:26:30: Sending PUBLISH to DROP-3_{id} (d0, q0, r1, m0, 'homeassistant/binary_sensor/<device>/config', ... (435 bytes))
```

This causes the DROP Connect app's MQTT connection screen to present connection information as if the connection to the broker failed. 

I updated my ACL with 
```
deny read homeassistant/<sensor>/<other_device>
read homeassistant/#
```

The hub successfully detects connection to the broker. This could also just be another fluke. 

Then I start seeing PUBLISH requests to drop_connect/discovery/. 

After adding drop_connect/discovery to the ACL, I am now seeing the discovery messages on the drop_connect/discovery topic (payload with: devDesc, devType, name). Home Assistant now has the DROP devices in the "Discovered" pane for configuration/adding!

Since those changes worked, I updated the Home Assistant user's (mqtt_drop) ACL to be:
```
user mqtt_drop
topic readwrite drop_connect/DROP-3_{id}/data/#
topic readwrite drop_connect/DROP-3_{id}/cmd/#
topic readwrite drop_connect/discovery/#
topic read homeassistant/status
```
(this can surely be shortened to readwrite drop_connect/#)

which seems to work. It is interesting to use the drop_connect/discovery/# topic, but also it makes sense if the user is not using the [default prefix](https://www.home-assistant.io/integrations/mqtt#mqtt-discovery) or the option cannot be presented in the UI.

Now time to make the password longer and keep an eye on sensor connections.

**Comment by pfrazer** [comment]
This is all good information.  Thanks for the time you're spending giving good feedback.

I just changed the DROP firmware to subscribe specifically to `homeassistant/status`, not to `homeassistant/#`.  The latter was added early in development because we _might_ want to use other information available from HA, but in the end all we really care about is knowing when HA has restarted.  I believe the problem you were seeing is related to the fact that a large number of status messages were being published to the DROP hub.  The TCP/IP receive buffers on the hub that handle incoming MQTT messages were sized to handle expected traffic, plus some overhead.  I suspect that the dump of retained MQTT messages on the `homeassistant/#` topic was overrunning the input buffers, causing the hub to reset its connection.  By preventing delivery of those messages via ACL, you're preventing the connection resets.  If I change the subscription to just `homeassistant/status` in the DROP firmware, the broker won't send those superfluous payloads in the first place.  Since not all HA users will know how to limit the traffic to DROP via ACL, I plan to release another hub firmware version containing this change soon.

> It is interesting to use the drop_connect/discovery/# topic

The discovery mechanism used by the DROP integration is actually separate from the mechanism used by the MQTT integration, so the discovery topic has to be outside of the `homeassistant/#` topic.  That did have the positive side-effect of not needing to configure the DROP hub with the Home Assistant topic prefix.  There are just a handful of integrations that do their own MQTT discovery, and placing the discovery topic where I did seems to match the common pattern.

> Now time to make the password longer and keep an eye on sensor connections.

DROP can handle MQTT passwords up to 100 characters in length.

**Comment by rewardone** [comment]
> I just changed the DROP firmware to subscribe specifically to `homeassistant/status`, not to `homeassistant/#`. The latter was added early in development because we _might_ want to use other information available from HA, but in the end all we really care about is knowing when HA has restarted. 

I initially thought that DROP might publish to homeassistant/{sensor}/# (e.g. placing valve in the homeassistant/valve/ topic, batteries in homeassistant/battery topic.). I think DROP having it's own topic is nice though. 

I disconnected my client and deleted all sensors in HA. Upgraded to 2.15 without any issue this time. Re-connected to MQTT. I see the specific subscribe to homeassistant/status and all sensors were discovered no problem. 

Huge kudos to your work and massive appreciation for exposing a local data integration option.

**Comment by pfrazer** [comment]
The DROP mobile apps and firmware needed to connect a DROP hub to Home Assistant are now fully available to all users.
